# @package _global_
defaults:
  - _self_

name:  real_lift_image_rel_realsease_webcam
dataset_path: data/metaquest_xarm_dataset.zarr

# required XARM robot configuration
use_relative_action: true # relative action mode

# dataset configuration
dataset:
  _target_: diffusion_policy.dataset.real_image_dataset.RealImageDataset
  dataset_path: ${dataset_path}
  horizon: 16
  pad_before: 1
  pad_after: 7
  n_obs_steps: 2
  abs_action: false  # Disable absolute action
  use_relative_action: ${use_relative_action}
  relative_type: ${relative_type}
  seed: 42
  val_ratio: 0.02

# shape_meta configuration remains unchanged
shape_meta:
  obs:
    agentview_image:
      shape: [3, 224, 224]
      type: rgb
    robot_eef_pose:
      shape: [6]
      type: low_dim
    robot_joint:
      shape: [7]
      type: low_dim
    robot_joint_vel:
      shape: [7]
      type: low_dim
    gripper:
      shape: [1]
      type: low_dim
  action:
    shape: [7]  # still 7D, but now it's relative action
    type: low_dim

  # Dataset Configuration for Zarr
dataset:
  _target_: diffusion_policy.dataset.real_image_dataset.RealImageDataset
  shape_meta: *shape_meta
  dataset_path: ${dataset_path}
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}
  n_obs_steps: ${dataset_obs_steps}
  abs_action: *abs_action
  rotation_rep: ${rotation_representation}
  use_legacy_normalizer: false
  min_episode_length: 10
  image_keys: ${camera_names}
  val_ratio: 0.02  # Reduce validation set ratio
  seed: 42
  use_cache: true  # Enable caching for acceleration

# Environment Runner Configuration (for evaluation)
env_runner:
  _target_: diffusion_policy.env_runner.xarm_real_runner.XarmRealRunner          # Use XarmRealRunner for real robot
  shape_meta: *shape_meta
  output_dir: ${output_dir}
  n_train: 10
  n_train_vis: 3
  train_start_seed: 0
  n_test: 50  # Increase number of test samples
  n_test_vis: 6
  test_start_seed: 100000
  max_steps: 400
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  render_obs_key: 'agentview_image'
  fps: 10
  crf: 22
  past_action: ${past_action_visible}
  abs_action: *abs_action
  tqdm_interval_sec: 5.0
  # XARM hardware configuration
  xarm_ip: "192.168.1.235"  # Update to your XARM actual IP
  camera_indices: [0]       # Camera device index
  eval_episodes: 10         # Number of episodes for each evaluation

  # Control parameters
  control_fps: 20.0
  inference_fps: 10.0
  action_horizon: ${horizon}
  use_relative_action: false

  # Safety parameters
  position_limits:
    - [200, -400, 100]    # xyz min (mm)
    - [700, 400, 600]     # xyz max (mm)
  velocity_limit: 100.0   # mm/s

  # Visualization parameters
  enable_video_recording: true
  save_obs: true

